# -*- coding: utf-8 -*-
"""calculator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m6W238r41ULsnPzmjgjPZuV5jBjB5op1
"""

# simple calculator

num1= float(input('Enter first number: '))
op= input('Enter operator(+, -, *, /): ')
num2= float(input('Enter second number: '))

if op=='+':
    print(num1+num2)
elif op=='-':
    print(num1-num2)
elif op=='*':
    print(num1*num2)
elif op=='/':
    print(num1/num2)
else:
    print('Invalid operator')